In [1]:
from __future__ import print_function
import torch

In [2]:
x=torch.empty(5,3)
print(x)

tensor([[5.9694e-39, 1.0010e-38, 1.0102e-38],
        [1.0561e-38, 1.0469e-38, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39]])


In [3]:
x=torch.rand(5,3)
print(x)

tensor([[0.6981, 0.9405, 0.9798],
        [0.4969, 0.8803, 0.2837],
        [0.9894, 0.2767, 0.0546],
        [0.1361, 0.2406, 0.8193],
        [0.0598, 0.0181, 0.8952]])


In [4]:
x=torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x= torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
#new_ * take in size
x=x.new_ones(5,3, dtype=torch.double)
print(x)

x= torch.randn_like( x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0386,  0.2192, -0.5177],
        [-1.3952,  0.2917, -0.2392],
        [ 0.2236,  1.2061, -1.2837],
        [ 0.6859, -0.6976, -0.2928],
        [-0.4548,  0.4637, -1.9080]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y= torch.rand( 5, 3)
print( x + y)

tensor([[-0.0249,  0.6249,  0.1913],
        [-0.8446,  1.2492,  0.4361],
        [ 0.9338,  1.7043, -0.5293],
        [ 1.2752, -0.4235,  0.5243],
        [-0.2314,  1.0094, -0.9657]])


In [9]:
#syntax 2
print(torch.add( x, y))

tensor([[-0.0249,  0.6249,  0.1913],
        [-0.8446,  1.2492,  0.4361],
        [ 0.9338,  1.7043, -0.5293],
        [ 1.2752, -0.4235,  0.5243],
        [-0.2314,  1.0094, -0.9657]])


In [10]:
result= torch.empty( 5, 3)
torch.add( x, y, out=result)
print(result)

tensor([[-0.0249,  0.6249,  0.1913],
        [-0.8446,  1.2492,  0.4361],
        [ 0.9338,  1.7043, -0.5293],
        [ 1.2752, -0.4235,  0.5243],
        [-0.2314,  1.0094, -0.9657]])


In [12]:
#adds x to y
y.add_(x)
print (y)

tensor([[-0.0249,  0.6249,  0.1913],
        [-0.8446,  1.2492,  0.4361],
        [ 0.9338,  1.7043, -0.5293],
        [ 1.2752, -0.4235,  0.5243],
        [-0.2314,  1.0094, -0.9657]])


In [13]:
print (x[ :, 1])

tensor([ 0.2192,  0.2917,  1.2061, -0.6976,  0.4637])


In [14]:
#resizing
x= torch.randn(4, 4)
y=x.view(16)
z=x.view(-1,8) #the size -1 inferred from other dim

print (x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.3496])
1.3496164083480835


In [18]:
#Converting torch tensor to a NumPy Array

In [19]:
a= torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b= a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
#Converting NumPy Array to Torch Tensor

In [24]:
import numpy as np
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [27]:
b=torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [28]:
np.add(a, 1, out=a)
print(b)
print(a)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]


In [29]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!